/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms_rtinder.MainModules;

import dbms_rtinder.Authentication.LoginPage;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import javax.imageio.ImageIO;
import jdk.nashorn.internal.codegen.CompilerConstants;

/**
 *
 * @author ritte
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        home = new javax.swing.JLabel();
        rtinderpro = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        profile1 = new javax.swing.JLabel();
        matches = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mateName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hobby = new javax.swing.JLabel();
        Dislike = new javax.swing.JLabel();
        like = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Here are some matches for you,");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1003, 628));
        jLayeredPane1.setOpaque(true);

        jLayeredPane2.setBackground(new java.awt.Color(255, 153, 255));
        jLayeredPane2.setOpaque(true);
        jLayeredPane2.setPreferredSize(new java.awt.Dimension(260, 678));

        jLayeredPane3.setBackground(new java.awt.Color(255, 153, 255));
        jLayeredPane3.setOpaque(true);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon("/dbms_rtinder/Resources/images/icon.jpg").
            getImage().getScaledInstance(211, 149, Image.SCALE_DEFAULT)));
    jLabel7.setText("jLabel7");
    jLabel7.setMaximumSize(new java.awt.Dimension(100, 150));
    jLabel7.setMinimumSize(new java.awt.Dimension(100, 150));
    jLabel7.setOpaque(true);
    jLabel7.setPreferredSize(new java.awt.Dimension(150, 150));

    jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("RTinder");

    userName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    userName.setForeground(new java.awt.Color(255, 255, 255));
    userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
    jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
    jSeparator1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

    jLayeredPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane3.setLayer(userName, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane3.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
    jLayeredPane3.setLayout(jLayeredPane3Layout);
    jLayeredPane3Layout.setHorizontalGroup(
        jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(69, 69, 69))
        .addGroup(jLayeredPane3Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jLayeredPane3Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(31, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jLayeredPane3Layout.setVerticalGroup(
        jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPane3Layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
            .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12))
    );

    home.setBackground(new java.awt.Color(255, 51, 255));
    home.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    home.setForeground(new java.awt.Color(255, 255, 255));
    home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    home.setText("Home");
    home.setOpaque(true);

    rtinderpro.setBackground(new java.awt.Color(255, 102, 255));
    rtinderpro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    rtinderpro.setForeground(new java.awt.Color(255, 255, 255));
    rtinderpro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    rtinderpro.setText("RTinder Pro");
    rtinderpro.setOpaque(true);
    rtinderpro.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            rtinderproMouseClicked(evt);
        }
    });

    profile.setBackground(new java.awt.Color(255, 102, 255));
    profile.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    profile.setForeground(new java.awt.Color(255, 255, 255));
    profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    profile.setText("Profile");
    profile.setOpaque(true);
    profile.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            profileMouseClicked(evt);
        }
    });

    profile1.setBackground(new java.awt.Color(255, 102, 255));
    profile1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    profile1.setForeground(new java.awt.Color(255, 255, 255));
    profile1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    profile1.setText("Sign out");
    profile1.setOpaque(true);
    profile1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            profile1MouseClicked(evt);
        }
    });

    matches.setBackground(new java.awt.Color(255, 102, 255));
    matches.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    matches.setForeground(new java.awt.Color(255, 255, 255));
    matches.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    matches.setText(" Matches");
    matches.setOpaque(true);
    matches.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            matchesMouseClicked(evt);
        }
    });

    jLayeredPane2.setLayer(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(home, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(rtinderpro, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(profile, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(profile1, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane2.setLayer(matches, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
    jLayeredPane2.setLayout(jLayeredPane2Layout);
    jLayeredPane2Layout.setHorizontalGroup(
        jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLayeredPane3)
        .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(rtinderpro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(profile1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(matches, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jLayeredPane2Layout.setVerticalGroup(
        jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPane2Layout.createSequentialGroup()
            .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
            .addComponent(matches, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(rtinderpro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(profile1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(17, 17, 17))
    );

    jPanel1.setBackground(new java.awt.Color(255, 204, 255));

    jLabel1.setBackground(new java.awt.Color(204, 204, 204));
    jLabel1.setOpaque(true);

    jLabel4.setBackground(new java.awt.Color(255, 255, 255));
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("Name");

    mateName.setForeground(new java.awt.Color(255, 255, 255));
    mateName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    jLabel5.setText("Age");

    age.setForeground(new java.awt.Color(255, 255, 255));
    age.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    jLabel6.setText("Hobby");

    hobby.setForeground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(126, 126, 126)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGap(108, 108, 108)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hobby)
                        .addComponent(age)
                        .addComponent(mateName))))
            .addContainerGap(113, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(47, 47, 47)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(50, 50, 50)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(mateName))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(age))
            .addGap(26, 26, 26)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(hobby))
            .addContainerGap(38, Short.MAX_VALUE))
    );

    Dislike.setBackground(new java.awt.Color(255, 0, 0));
    Dislike.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    Dislike.setText("Dislike");
    Dislike.setOpaque(true);
    Dislike.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            DislikeMouseClicked(evt);
        }
    });

    like.setBackground(new java.awt.Color(51, 255, 51));
    like.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    like.setText("Like");
    like.setOpaque(true);
    like.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            likeMouseClicked(evt);
        }
    });

    msg.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    msg.setForeground(new java.awt.Color(0, 0, 0));
    msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    jLayeredPane1.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(Dislike, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(like, javax.swing.JLayeredPane.DEFAULT_LAYER);
    jLayeredPane1.setLayer(msg, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
    jLayeredPane1.setLayout(jLayeredPane1Layout);
    jLayeredPane1Layout.setHorizontalGroup(
        jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jLayeredPane1Layout.createSequentialGroup()
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(124, 124, 124)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(Dislike, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(like, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(139, Short.MAX_VALUE))
    );
    jLayeredPane1Layout.setVerticalGroup(
        jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        .addGroup(jLayeredPane1Layout.createSequentialGroup()
            .addGap(73, 73, 73)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(Dislike, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addComponent(like, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rtinderproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rtinderproMouseClicked
        this.dispose();
        RTinderPro rTinderPro=new RTinderPro();
        rTinderPro.setUserID(UserID);
        rTinderPro.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_rtinderproMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        this.dispose();
        MyProfile myProfile=new MyProfile();
        myProfile.setUserID(UserID);
        myProfile.displayProfile();
        myProfile.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_profileMouseClicked

    private void profile1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile1MouseClicked

        this.dispose();
        LoginPage loginPage=new LoginPage();
        loginPage.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_profile1MouseClicked

    private void likeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_likeMouseClicked
   
        try{
        Statement statementl=null;
        String likeQuery="Update `match` set status='like' where UserUID='"+UserID+"' AND mate ='"+id+"'";
        statementl=dbms_rtinder.Dbms_rtinder.getInstance().getConnection().createStatement();
        statementl.executeUpdate(likeQuery);
        showNextMatch();
        }
        catch(Exception exception){
            System.out.println(exception.getMessage());
        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_likeMouseClicked

    private void DislikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DislikeMouseClicked
 
        try{
        Statement statementd=null;
        String dislikeQuery="Update `match` set status='dislike' where UserUID='"+UserID+"' AND mate ='"+id+"'";
        statementd=dbms_rtinder.Dbms_rtinder.getInstance().getConnection().createStatement();
        statementd.executeUpdate(dislikeQuery);
        showNextMatch();
        }
        catch(Exception exception){
            System.out.println(exception.getMessage());
        }

// TODO add your handling code here:
    }//GEN-LAST:event_DislikeMouseClicked

    private void matchesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matchesMouseClicked
        this.dispose();
        Matches matches=new Matches();
        matches.setUserID(UserID);
        matches.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_matchesMouseClicked

    public void showNextMatch() throws Exception{
        
       Statement statementn=null;
       String matchQ="Select * from `match` where UserUID='"+UserID+"' and Shown='False'";
       statementn=dbms_rtinder.Dbms_rtinder.getInstance().getConnection().createStatement();
       ResultSet resultSetn=statementn.executeQuery(matchQ);
        System.out.println("Before while loop");
            
      while(resultSetn.next()){
          
          Statement statementu=null;
          id=resultSetn.getString("mate");
          System.out.println("After entering the while loop"+id);
            String updateQ="Update `match` set Shown='True' where UserUID='"+UserID+"' and mate='"+id+"'";
            statementu=dbms_rtinder.Dbms_rtinder.getInstance().getConnection().createStatement();
            statementu.executeUpdate(updateQ);
            System.out.println("After update query");
            Statement statementa=null;
            String nextQ ="Select * from `userprofile` where Unique_ID='"+id+"'";
            statementa=dbms_rtinder.Dbms_rtinder.getInstance().getConnection().createStatement();
            ResultSet resultSetnm=statementa.executeQuery(nextQ);
            while(resultSetnm.next()){
            String mname=resultSetnm.getString("Name");
                System.out.println(mname);
            String age=resultSetnm.getString("Age");
                System.out.println(age);
            String hobby=resultSetnm.getString("Hobby");
                System.out.println(hobby);
            mateName.setText(mname);
            this.age.setText(age);
            this.hobby.setText(hobby);
            break;
            }
            
            break;

        }
      //if(resultSetn.next()==false){
        //     mateName.setText(" ");
       //     this.age.setText(" ");
       //    this.hobby.setText(" ");
      //    msg.setText("No more matches for now !");
      // }
        
    }
    public void setUserID(String userID) {    
        UserID=userID;
        try {
        Statement statement=null;
        String userQuery="Select * FROM userprofile WHERE Unique_ID='"+userID+"'";
        statement=dbms_rtinder.Dbms_rtinder.getInstance().getConnection().createStatement();
        ResultSet resultSet=statement.executeQuery(userQuery);
        while(resultSet.next()){
        name=resultSet.getString("Name");
        sex=resultSet.getString("Sex");
        System.out.println(name);
        userName.setText(name);
        }
        showNextMatch();
             
        } catch (Exception e) {
            System.out.println("Error in class homepage");
            System.out.println(e.getMessage());
        }
        
    }
    public void checkNewMatches(){
        
         try {
        Statement statement=null;
        String checkQuery="SELECT UserUID FROM `match` where mate='"+UserID+"'";
        statement=dbms_rtinder.Dbms_rtinder.getInstance().getConnection().createStatement();
        ResultSet resultSet=statement.executeQuery(checkQuery);
        while(resultSet.next()){
            String id=resultSet.getString("UserUID");
            if(alreadyChecked(UserID, id)!=true){
            Statement statementa=null;
            String insertQuery ="INSERT INTO rtinder.`match` (`UserUID`, Mate, `Shown`) VALUES ('"+UserID+"','"+id+"', 'False') ";
            statementa=dbms_rtinder.Dbms_rtinder.getInstance().getConnection().createStatement();
            statementa.executeUpdate(insertQuery);
            }

        }
                
        } catch (Exception e) {
            System.out.println("Error in class homepage");
            System.out.println(e.getMessage());
        }
    }
    
    public boolean alreadyChecked(String uid,String mid) throws Exception{
        Statement statementc=null;
        String checkQuery="Select * FROM `match` WHERE `UserUID` = '"+uid+"' AND `Mate` = '"+mid+"' AND (`Shown` = 'False' or `Shown`='True');";
        statementc=dbms_rtinder.Dbms_rtinder.getInstance().getConnection().createStatement();
        ResultSet resultSetc=statementc.executeQuery(checkQuery);
        if(resultSetc.next()){
            return true;
        }else{
            return false;
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                new HomePage().setVisible(true);
            }
        });
    }
    private String id;
    private String UserID;
    private static String name;
    private static String sex;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dislike;
    private javax.swing.JLabel age;
    private javax.swing.JLabel hobby;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel like;
    private javax.swing.JLabel matches;
    private javax.swing.JLabel mateName;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel profile1;
    private javax.swing.JLabel rtinderpro;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
